Repository player-ui/tools, pull requests merged in 2023-02, with the labels that each got.

#40 add forked pr workflow
  .circleci/config.yml
Labels: skip-release

#36 Bugfix/long lists
  xlr/converters/src/__tests__/__snapshots__/ts-to-common.test.ts.snap
  xlr/converters/src/__tests__/ts-to-common.test.ts
  xlr/converters/src/ts-to-xlr.ts
Labels: patch

#38 feat: adds support for @metatag
  xlr/converters/src/__tests__/__snapshots__/player.test.ts.snap
  xlr/converters/src/__tests__/player.test.ts
  xlr/types/src/core.ts
  xlr/utils/src/__tests__/__snapshots__/annotations.test.ts.snap
  xlr/utils/src/__tests__/annotations.test.ts
  xlr/utils/src/annotations.ts
  xlr/utils/src/test-helpers.ts
Labels: minor
