Repository player-ui/tools, pull requests merged in 2024-07, with the labels that each got.

#147 revert canary on forks
  .github/workflows/canary.yml
Labels: skip-release

#146 Update CLI to Allow Compilation to any File Type
  cli/src/commands/dsl/compile.ts
  cli/src/utils/compilation-context.ts
Labels: minor

#153 Re-add compiler formatting to dsl output
  cli/src/utils/compilation-context.ts
Labels: patch
