Repository player-ui/tools, pull requests merged in 2024-08, with the labels that each got.

#155 Fix Source Maps not Being Generated for DSL Content
  cli/bin/dev
  cli/bin/run
Labels: patch

#159 feat: doesn't exit with error if warn-only on dsl validation
  cli/src/commands/dsl/compile.ts
  cli/src/commands/dsl/validate.ts
Labels: minor

#163 Update Rules Versions
  MODULE.bazel
  MODULE.bazel.lock
  cli/BUILD
  package.json
  pnpm-lock.yaml
Labels: skip-release
